sequenceDiagram
    participant browser
    participant server
    
    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    activate server
    server-->>browser: {"message":"note created"}
    deactivate server

    Note left of server: "Status code: 201 Created"
    Note right of browser: The browser executes the callback function that renders the notes
    Note right of browser: The server response executes only the new_note_spa file, not all files